#server:
 # port:8080

#spring:
 # datasource:
  #  url:  jdbc:mysql://localhost:3306/javatechie
   # username: root
    #password: root
    #driverClassName: com.mysql.cj.jdbc.Driver
 # jpa:
  #  properties:
   #   hibernate:
    #    dialect : org.hibernate.dialect.MySQL5InnoDBDialect
     #   ddl-auto: update
    #show-sql: true
